apiVersion: v1
kind: Namespace
metadata:
  name: k8s-vm-app
  labels:
    name: k8s-vm-app
    environment: production
    team: devops
  annotations:
    description: "Namespace for the k8s-vm-app application"